export { discoverCommands, discoverRepository } from "./discover.js";
export type { DiscoveredCommand, Discovery, DiscoveryModule } from "./discover.js";
export { classifyProjectPath, routesInFile } from "./stacks/index.js";
export type { RouteHit } from "./stacks/surfaces.js";
export type { FileClassification } from "./stacks/types.js";
export { initProject } from "./init.js";
export type { InitResult } from "./init.js";
export { linkCommandCriterion } from "./link.js";
export { loadProject } from "./load.js";
export type { EnvironmentPolicy, ProjectConfig, SecurityPolicy, ShellCommandConfig, UiPolicy } from "./schema.js";
